PATH = "Buglien"
CONFIG = [
    {
        'id': 1,
        'name': 'background',
        'directory': '1-background',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 2,
        'name': 'weapon',
        'directory': '2-weapon',
        'required': False,
        'rarity_weights': 100,
    },
    {
        'id': 3,
        'name': 'body',
        'directory': '3-body',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 4,
        'name': 'clothing',
        'directory': '4-clothing',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 5,
        'name': 'pattern',
        'directory': '5-pattern',
        'required': False,
        'rarity_weights': None,
    },
    {
        'id': 6,
        'name': 'tattoo',
        'directory': '6-tattoo',
        'required': False,
        'rarity_weights': None,
    },
    {
        'id': 7,
        'name': 'eyes',
        'directory': '7-eyes',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 8,
        'name': 'glow',
        'directory': '8-glow',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 9,
        'name': 'nose',
        'directory': '9-nose',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 10,
        'name': 'mouth',
        'directory': '10-mouth',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 11,
        'name': 'glasses',
        'directory': '11-glasses',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 12,
        'name': 'accessory',
        'directory': '12-accessory',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 13,
        'name': 'horn',
        'directory': '13-horn',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 14,
        'name': 'mask',
        'directory': '14-mask',
        'required': True,
        'rarity_weights': None,
    },
]
