PATH = "Human"
CONFIG = [
    {
        'id': 1,
        'name': 'background',
        'directory': '1-background',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 2,
        'name': 'weapon',
        'directory': '2-weapon',
        'required': False,
        'rarity_weights': 100,
    },
    {
        'id': 3,
        'name': 'face',
        'directory': '3-face',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 4,
        'name': 'tattoo',
        'directory': '4-tattoo',
        'required': False,
        'rarity_weights': None,
    },
    {
        'id': 5,
        'name': 'eyes',
        'directory': '5-eyes',
        'required': False,
        'rarity_weights': None,
    },
    {
        'id': 6,
        'name': 'nose',
        'directory': '6-nose',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 7,
        'name': 'hair',
        'directory': '7-hair',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 8,
        'name': 'glow',
        'directory': '8-glow',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 9,
        'name': 'mouth',
        'directory': '9-mouth',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 10,
        'name': 'body',
        'directory': '10-body',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 11,
        'name': 'clothing',
        'directory': '11-clothing',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 12,
        'name': 'glasses',
        'directory': '12-glasses',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 13,
        'name': 'accessory',
        'directory': '13-accessory',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 14,
        'name': 'headgear',
        'directory': '14-headgear',
        'required': True,
        'rarity_weights': None,
    },
    {
        'id': 15,
        'name': 'mask',
        'directory': '15-mask',
        'required': True,
        'rarity_weights': None,
    },
]
